import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'changelog',
    {type: 'autogenerated', dirName: 'getting-started'},
    {type: 'autogenerated', dirName: 'concepts'},
    {type: 'autogenerated', dirName: 'integrations'},
    {type: 'autogenerated', dirName: 'tutorials'},
    {type: 'autogenerated', dirName: 'api-reference'},
  ],
};

export default sidebars;
